server: 
  port: 9004
spring: 
  application:  
    name: chenyj-article #指定服务名
  datasource:  
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chenyj_article?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: cyj7416146
  jpa: 
    database: MySQL
    show-sql: true

#    配置redis
  redis:
    host: 192.168.1.141
    password: cyj7416146
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true