server:
  port: 12000
spring:
  application:
    name: chenyj-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/chenyinjie/configuration_file.git
  rabbitmq:
    host: 192.168.1.140
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: "*"
#  endpoint:
#    bus-refresh:
#      enabled: true