server:
  port: 9012
  connection-timeout: 100
spring:
  application:
    name: chenyj-web
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

jwt:
  config:
    key: itcast

zuul:
#设置敏感header不过滤
  sensitive-headers:
  routes:
    chenyj-base:
      path: /base/**
      serviceId: chenyj-base
    chenyj-qa:
      path: /qa/**
      serviceId: chenyj-qa
    chenyj-user:
      path: /user/**
      serviceId: chenyj-user
    chenyj-friend:
      path: /friend/**
      serviceId: chenyj-friend