server: 
  port: 9001
spring: 
  application:  
    name: chenyj-recruit #指定服务名
  datasource:  
    driverClassName: [driverName]
    url: [url]
    username: root
    password: cyj7416146
  jpa: 
    database: MySQL
    show-sql: true
